# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d767387c148a7423a0744cb5351ea5da"
name = "pulse-checkout"
handle = "pulse-checkout"
application_url = "https://kruger-rid-johns-familiar.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "pulse-checkout.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://kruger-rid-johns-familiar.trycloudflare.com/auth/callback",
  "https://kruger-rid-johns-familiar.trycloudflare.com/auth/shopify/callback",
  "https://kruger-rid-johns-familiar.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
